// This file is auto-generated by scripts/generate-widget-registry.js.
// Do not edit this file manually. Any changes will be overwritten.
import React from 'react';

import { AiBarWidget } from '../../../src/widgets/ai/AiBarWidget';
import { AiChatWidget } from '../../../src/widgets/ai/AiChatWidget';
import { AiSummaryWidget } from '../../../src/widgets/ai/AiSummaryWidget';
import { AgendaWidget } from '../../../src/widgets/calendar/AgendaWidget';
import { CalendarMonthly } from '../../../src/widgets/calendar/CalendarMonthly';
import { YearProgress } from '../../../src/widgets/calendar/YearProgress';
import { AnalogClock } from '../../../src/widgets/clock/AnalogClock';
import { DigitalClock } from '../../../src/widgets/clock/DigitalClock';
import { FlipClock } from '../../../src/widgets/clock/FlipClock';
import { StopwatchWidget } from '../../../src/widgets/clock/StopwatchWidget';
import { CicdPipeline } from '../../../src/widgets/developer/CicdPipeline';
import { CpuMonitor } from '../../../src/widgets/developer/CpuMonitor';
import { GithubGrid } from '../../../src/widgets/developer/GithubGrid';
import { FinanceStockCrypto } from '../../../src/widgets/finance/FinanceStockCrypto';
import { BreathingWidget } from '../../../src/widgets/health/BreathingWidget';
import { StepsWidget } from '../../../src/widgets/health/StepsWidget';
import { WaterWidget } from '../../../src/widgets/health/WaterWidget';
import { CalculatorWidget } from '../../../src/widgets/productivity/CalculatorWidget';
import { CameraWidget } from '../../../src/widgets/productivity/CameraWidget';
import { FocusWidget } from '../../../src/widgets/productivity/FocusWidget';
import { FolderWidget } from '../../../src/widgets/productivity/FolderWidget';
import { GoogleSearchWidget } from '../../../src/widgets/productivity/GoogleSearchWidget';
import { MusicWidget } from '../../../src/widgets/productivity/MusicWidget';
import { PhotoFrameWidget } from '../../../src/widgets/productivity/PhotoFrameWidget';
import { PomodoroWidget } from '../../../src/widgets/productivity/PomodoroWidget';
import { TextUsernameWidget } from '../../../src/widgets/productivity/TextUsernameWidget';
import { TodoWidget } from '../../../src/widgets/productivity/TodoWidget';
import { BatteryWidget } from '../../../src/widgets/smart_home/BatteryWidget';
import { BluetoothWidget } from '../../../src/widgets/smart_home/BluetoothWidget';
import { QuickControlsWidget } from '../../../src/widgets/smart_home/QuickControlsWidget';
import { SmartHomeControls } from '../../../src/widgets/smart_home/SmartHomeControls';
import { SoundControlWidget } from '../../../src/widgets/smart_home/SoundControlWidget';
import { TorchWidget } from '../../../src/widgets/smart_home/TorchWidget';
import { ContactWidget } from '../../../src/widgets/social/ContactWidget';
import { SocialFeed } from '../../../src/widgets/social/SocialFeed';
import { SocialShortcutsWidget } from '../../../src/widgets/social/SocialShortcutsWidget';
import { MoonPhaseWidget } from '../../../src/widgets/weather/MoonPhaseWidget';
import { WeatherAqi } from '../../../src/widgets/weather/WeatherAqi';
import { WeatherCurrent } from '../../../src/widgets/weather/WeatherCurrent';

export function getWidgetComponent(templateId: string): React.ComponentType<any> {
  switch (templateId) {
    case 'ai_bar':
      return AiBarWidget;
    case 'ai_chat':
      return AiChatWidget;
    case 'ai_summary':
      return AiSummaryWidget;
    case 'calendar_agenda':
      return AgendaWidget;
    case 'calendar_monthly':
      return CalendarMonthly;
    case 'calendar_progress':
      return YearProgress;
    case 'clock_analog':
      return AnalogClock;
    case 'clock_digital':
      return DigitalClock;
    case 'clock_dot':
      return DigitalClock;
    case 'clock_flip':
      return FlipClock;
    case 'clock_stopwatch':
      return StopwatchWidget;
    case 'developer_battery':
      return BatteryWidget;
    case 'developer_build':
      return CicdPipeline;
    case 'developer_cpu':
      return CpuMonitor;
    case 'developer_git':
      return GithubGrid;
    case 'developer_quick_controls':
      return QuickControlsWidget;
    case 'finance_crypto':
      return FinanceStockCrypto;
    case 'health_breath':
      return BreathingWidget;
    case 'health_steps':
      return StepsWidget;
    case 'health_water':
      return WaterWidget;
    case 'productivity_calculator':
      return CalculatorWidget;
    case 'productivity_camera':
      return CameraWidget;
    case 'productivity_focus':
      return FocusWidget;
    case 'productivity_folder':
      return FolderWidget;
    case 'productivity_google_search':
      return GoogleSearchWidget;
    case 'productivity_music':
      return MusicWidget;
    case 'productivity_photo_frame':
      return PhotoFrameWidget;
    case 'productivity_pomodoro':
      return PomodoroWidget;
    case 'productivity_text_username':
      return TextUsernameWidget;
    case 'productivity_todo':
      return TodoWidget;
    case 'smart_home_bluetooth':
      return BluetoothWidget;
    case 'smart_home_controls':
      return SmartHomeControls;
    case 'smart_home_sound_control':
      return SoundControlWidget;
    case 'smart_home_torch':
      return TorchWidget;
    case 'social_contact':
      return ContactWidget;
    case 'social_feed':
      return SocialFeed;
    case 'social_shortcuts':
      return SocialShortcutsWidget;
    case 'weather_aqi':
      return WeatherAqi;
    case 'weather_current':
      return WeatherCurrent;
    case 'weather_moon_phase':
      return MoonPhaseWidget;
    default:
      throw new Error(`[WidgetRegistry] Unknown widget template ID: ${templateId}`);
  }
}
